Repository Guam-Hydrologic-Survey/well-nitrates-app, pull requests merged in 2023-02, with the labels that each got.

#24 Develop
  DOCS.md
  index.html
  package-lock.json
  package.json
  static/js/main.js
Labels: bug, enhancement

#25 Revert "Develop"
  DOCS.md
  index.html
  package-lock.json
  package.json
  static/js/main.js
Labels: bug

#26 adding drawing features, removed measure tool
  index.html
  static/js/main.js
Labels: bug, enhancement

#27 added comment for leaflet search control
  index.html
Labels: documentation

#29 updated names and labels as nitrate-n
  index.html
  static/js/main.js
Labels: enhancement

#30 Develop
  index.html
  static/assets/WERI-Logo-Name.ico
  static/assets/WERI-Logo.ico
Labels: enhancement
